import 'package:cloud_firestore/cloud_firestore.dart';

final List<Map<String, dynamic>> kuRestaurants = [
  {
    "name": "ม่าม่าพร",
    "desc": "ขึ้นชื่อเรื่องยำมาม่ารสแซ่บ เครื่องแน่น (ราคานักศึกษา)",
    "category": "food",
    "imageUrl": "",
    "address": "มหาวิทยาลัยเกษตรศาสตร์ บางเขน",
    "openTime": "08:00",
    "closeTime": "17:00",
    "avgRating": 0,
    "ratingCount": 0,
    "ratingSum": 0,
    "createdAt": FieldValue.serverTimestamp(),
  },
  {
    "name": "โรงอาหารกลาง 1 (บาร์ใหม่)",
    "desc": "โรงอาหารยอดนิยม ใกล้โซนเรียน ร้านอาหารหลากหลาย",
    "category": "food",
    "imageUrl": "",
    "address": "มหาวิทยาลัยเกษตรศาสตร์ บางเขน",
    "openTime": "06:00",
    "closeTime": "21:00",
    "avgRating": 0,
    "ratingCount": 0,
    "ratingSum": 0,
    "createdAt": FieldValue.serverTimestamp(),
  },
  {
    "name": "โรงอาหารกลาง 2 (บาร์ใหม่กว่า)",
    "desc": "โรงอาหารขนาดใหญ่ ใกล้คณะวิศวะ",
    "category": "food",
    "imageUrl": "",
    "address": "มหาวิทยาลัยเกษตรศาสตร์ บางเขน",
    "openTime": "06:00",
    "closeTime": "15:30",
    "avgRating": 0,
    "ratingCount": 0,
    "ratingSum": 0,
    "createdAt": FieldValue.serverTimestamp(),
  },
  {
    "name": "ศูนย์อาหารคณะวิทยาศาสตร์",
    "desc": "ศูนย์อาหารสำหรับนิสิตวิทยาศาสตร์ ราคานักศึกษา",
    "category": "food",
    "imageUrl": "",
    "address": "มหาวิทยาลัยเกษตรศาสตร์ บางเขน",
    "openTime": "07.00",
    "closeTime": "16:00",
    "avgRating": 0,
    "ratingCount": 0,
    "ratingSum": 0,
    "createdAt": FieldValue.serverTimestamp(),
  },
  {
    "name": "โรงอาหารคณะบริหารธุรกิจ",
    "desc": "โรงอาหารใกล้คณะบริหารธุรกิจ",
    "category": "food",
    "imageUrl": "",
    "address": "มหาวิทยาลัยเกษตรศาสตร์ บางเขน",
    "openTime": "06:30",
    "closeTime": "18:30",
    "avgRating": 0,
    "ratingCount": 0,
    "ratingSum": 0,
    "createdAt": FieldValue.serverTimestamp(),
  },
  {
    "name": "โรงอาหารคณะสัตวแพทยศาสตร์",
    "desc": "โรงอาหารใกล้คณะสัตวแพทยศาสตร์ ใกล้กับคณะเทคนิคการสัตวแพทย์",
    "category": "food",
    "imageUrl": "",
    "address": "มหาวิทยาลัยเกษตรศาสตร์ บางเขน",
    "openTime": "05.00",
    "closeTime": "19.00",
    "avgRating": 0,
    "ratingCount": 0,
    "ratingSum": 0,
    "createdAt": FieldValue.serverTimestamp(),
  },
  {
    "name": "โรงอาหารคณะวนศาสตร์",
    "desc": "โรงอาหารใกล้คณะวนศาสตร์",
    "category": "food",
    "imageUrl": "",
    "address": "มหาวิทยาลัยเกษตรศาสตร์ บางเขน",
    "openTime": "06:00",
    "closeTime": "15:00",
    "avgRating": 0,
    "ratingCount": 0,
    "ratingSum": 0,
    "createdAt": FieldValue.serverTimestamp(),
  },
  {
    "name": "ศูนย์อาหารคณะวิศวกรรมศาสตร์",
    "desc": "ศูนย์อาหารใกล้ตึกเรียนวิศวะ",
    "category": "food",
    "imageUrl": "",
    "address": "มหาวิทยาลัยเกษตรศาสตร์ บางเขน",
    "openTime": "05:30",
    "closeTime": "18:00",
    "avgRating": 0,
    "ratingCount": 0,
    "ratingSum": 0,
    "createdAt": FieldValue.serverTimestamp(),
  },
  {
    "name": "โรงอาหารคณะสถาปัตยกรรมศาสตร์",
    "desc": "ศูนย์อาหารใกล้คณะสถาปัตยกรรมศาสตร์",
    "category": "food",
    "imageUrl": "",
    "address": "มหาวิทยาลัยเกษตรศาสตร์ บางเขน",
    "openTime": "05:00",
    "closeTime": "18:00",
    "avgRating": 0,
    "ratingCount": 0,
    "ratingSum": 0,
    "createdAt": FieldValue.serverTimestamp(),
  },
  {
    "name": "ศูนย์อาหารคณะเกษตร",
    "desc": "ศูนย์อาหารโซนคณะเกษตร",
    "category": "food",
    "imageUrl": "",
    "address": "มหาวิทยาลัยเกษตรศาสตร์ บางเขน",
    "openTime": "07:00",
    "closeTime": "15:00",
    "avgRating": 0,
    "ratingCount": 0,
    "ratingSum": 0,
    "createdAt": FieldValue.serverTimestamp(),
  },

  {
    "name": "MaxBeef Yakinikux",
    "desc": "ร้านบรรยากาศสไตล์คาเฟ่ (ราคานักศึกษา)",
    "category": "food",
    "imageUrl": "",
    "address": "มหาวิทยาลัยเกษตรศาสตร์ บางเขน",
    "openTime": "10:00",
    "closeTime": "19:00",
    "avgRating": 0,
    "ratingCount": 0,
    "ratingSum": 0,
    "createdAt": FieldValue.serverTimestamp(),
  },

  // ☕ CAFE
  {
    "name": "A.R.T. - Art of Coffee",
    "desc": "คาเฟ่กาแฟพิเศษ บรรยากาศชิล",
    "category": "cafe",
    "imageUrl": "",
    "address": "มหาวิทยาลัยเกษตรศาสตร์ บางเขน",
    "openTime": "07:00",
    "closeTime": "16:00",
    "avgRating": 0,
    "ratingCount": 0,
    "ratingSum": 0,
    "createdAt": FieldValue.serverTimestamp(),
  },
  {
    "name": "เนสกาแฟ สตรีท คาเฟ่",
    "desc": "กาแฟพร้อมดื่ม",
    "category": "cafe",
    "imageUrl": "",
    "address": "มหาวิทยาลัยเกษตรศาสตร์ บางเขน",
    "openTime": "07:00",
    "closeTime": "18:00",
    "avgRating": 0,
    "ratingCount": 0,
    "ratingSum": 0,
    "createdAt": FieldValue.serverTimestamp(),
  },
  {
    "name": "Starbucks ตรงข้ามคณะบริหารฯ",
    "desc": "ร้านกาแฟแบรนด์ดัง นั่งทำงาน พบปะเพื่อน",
    "category": "cafe",
    "imageUrl": "",
    "address": "มหาวิทยาลัยเกษตรศาสตร์ บางเขน",
    "openTime": "07:00",
    "closeTime": "19:00",
    "avgRating": 0,
    "ratingCount": 0,
    "ratingSum": 0,
    "createdAt": FieldValue.serverTimestamp(),
  },
  {
    "name": "Cafe Amazon สาขา อาคารพันธุ์ไม้",
    "desc": "คาเฟ่กาแฟและเครื่องดื่มใกล้คณะ",
    "category": "cafe",
    "imageUrl": "",
    "address": "มหาวิทยาลัยเกษตรศาสตร์ บางเขน",
    "openTime": "07:00",
    "closeTime": "17:00",
    "avgRating": 0,
    "ratingCount": 0,
    "ratingSum": 0,
    "createdAt": FieldValue.serverTimestamp(),
  },
  {
    "name": "Inthanin Coffee KU",
    "desc": "ร้านกาแฟบรรยากาศชิลในมหาลัย",
    "category": "cafe",
    "imageUrl": "",
    "address": "มหาวิทยาลัยเกษตรศาสตร์ บางเขน",
    "openTime": "",
    "closeTime": "",
    "avgRating": 0,
    "ratingCount": 0,
    "ratingSum": 0,
    "createdAt": FieldValue.serverTimestamp(),
  },
  {
    "name": "True Coffee KU",
    "desc": "คาเฟ่นั่งทำงาน อ่านหนังสือ",
    "category": "cafe",
    "imageUrl": "",
    "address": "มหาวิทยาลัยเกษตรศาสตร์ บางเขน",
    "openTime": "07:00",
    "closeTime": "18:00",
    "avgRating": 0,
    "ratingCount": 0,
    "ratingSum": 0,
    "createdAt": FieldValue.serverTimestamp(),
  },
  {
    "name": "Bagbag Brew Coffee",
    "desc": "คาเฟ่นั่งทำงาน มี Wi-Fi",
    "category": "cafe",
    "imageUrl": "",
    "address": "มหาวิทยาลัยเกษตรศาสตร์ บางเขน",
    "openTime": "07:00",
    "closeTime": "17:00",
    "avgRating": 0,
    "ratingCount": 0,
    "ratingSum": 0,
    "createdAt": FieldValue.serverTimestamp(),
  },

   {
    "name": "SISKU COFFEE",
    "desc": "โดดเด่นด้วยเมนูเครื่องดื่มหลากหลาย",
    "category": "cafe",
    "imageUrl": "",
    "address": "มหาวิทยาลัยเกษตรศาสตร์ บางเขน",
    "openTime": "07:00",
    "closeTime": "17:00",
    "avgRating": 0,
    "ratingCount": 0,
    "ratingSum": 0,
    "createdAt": FieldValue.serverTimestamp(),
  },
  {
    "name": "Yoguruto ชั้น 1 อาคารวิศวกรรมสิ่งแวดล้อม",
    "desc": "โยเกิร์ตสดปั่นสไตล์ญี่ปุ่น เนื้อเนียน",
    "category": "cafe",
    "imageUrl": "",
    "address": "มหาวิทยาลัยเกษตรศาสตร์ บางเขน",
    "openTime": "09:00",
    "closeTime": "17:30",
    "avgRating": 0,
    "ratingCount": 0,
    "ratingSum": 0,
    "createdAt": FieldValue.serverTimestamp(),
  },
  {
    "name": "Chama - ชามะ ชาไข่มุกระเบิด",
    "desc": "ชานมไข่มุกและชาผลไม้",
    "category": "cafe",
    "imageUrl": "",
    "address": "มหาวิทยาลัยเกษตรศาสตร์ บางเขน",
    "openTime": "09:00",
    "closeTime": "19:00",
    "avgRating": 0,
    "ratingCount": 0,
    "ratingSum": 0,
    "createdAt": FieldValue.serverTimestamp(),
  },
  {
    "name": "Beleaf & juice Shop",
    "desc": "น้ำผลไม้ปั่น สดชื่น",
    "category": "cafe",
    "imageUrl": "",
    "address": "มหาวิทยาลัยเกษตรศาสตร์ บางเขน",
    "openTime": "11:00",
    "closeTime": "20:00",
    "avgRating": 0,
    "ratingCount": 0,
    "ratingSum": 0,
    "createdAt": FieldValue.serverTimestamp(),
  },
];

String generateDocId(String name) {
  return name
      .toLowerCase()
      .trim()
      .replaceAll(RegExp(r'\s+'), '')
      .replaceAll(RegExp(r'[^\u0E00-\u0E7Fa-z0-9]'), '');
}

Future<void> seedRestaurants() async {
  final col = FirebaseFirestore.instance.collection('restaurants');

  for (final r in kuRestaurants) {
    final name = r['name'] as String;
    final id = generateDocId(name);

    final data = {
      ...r,

      // 🔥 เพิ่ม field ใหม่
      "latitude": null,      // double?
      "longitude": null,     // double?
      "location": null,      // GeoPoint?
      "googleMapsUrl": null, // String?

      "createdAt": FieldValue.serverTimestamp(),
      "updatedAt": FieldValue.serverTimestamp(),
    };

    await col.doc(id).set(data); // ไม่มี merge
  }

  print("✅ Restaurants collection created successfully");
}
